/*
 * Charges
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.malga.model.charges;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.malga.model.charges.PaymentMethodBoleto;
import io.malga.model.charges.PaymentMethodBoletoFine;
import io.malga.model.charges.PaymentMethodBoletoInterest;
import io.malga.model.charges.PaymentMethodCard;
import io.malga.model.charges.PaymentMethodPix;
import java.io.IOException;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import io.malga.model.charges.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-28T20:17:02.961685-03:00[America/Sao_Paulo]")
public class ChargeRequestPaymentMethod extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ChargeRequestPaymentMethod.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ChargeRequestPaymentMethod.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ChargeRequestPaymentMethod' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PaymentMethodBoleto> adapterPaymentMethodBoleto = gson.getDelegateAdapter(this, TypeToken.get(PaymentMethodBoleto.class));
            final TypeAdapter<PaymentMethodCard> adapterPaymentMethodCard = gson.getDelegateAdapter(this, TypeToken.get(PaymentMethodCard.class));
            final TypeAdapter<PaymentMethodPix> adapterPaymentMethodPix = gson.getDelegateAdapter(this, TypeToken.get(PaymentMethodPix.class));

            return (TypeAdapter<T>) new TypeAdapter<ChargeRequestPaymentMethod>() {
                @Override
                public void write(JsonWriter out, ChargeRequestPaymentMethod value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `PaymentMethodBoleto`
                    if (value.getActualInstance() instanceof PaymentMethodBoleto) {
                        JsonObject obj = adapterPaymentMethodBoleto.toJsonTree((PaymentMethodBoleto)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `PaymentMethodCard`
                    if (value.getActualInstance() instanceof PaymentMethodCard) {
                        JsonObject obj = adapterPaymentMethodCard.toJsonTree((PaymentMethodCard)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `PaymentMethodPix`
                    if (value.getActualInstance() instanceof PaymentMethodPix) {
                        JsonObject obj = adapterPaymentMethodPix.toJsonTree((PaymentMethodPix)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: PaymentMethodBoleto, PaymentMethodCard, PaymentMethodPix");
                }

                @Override
                public ChargeRequestPaymentMethod read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    // deserialize PaymentMethodBoleto
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PaymentMethodBoleto.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'PaymentMethodBoleto'");
                        ChargeRequestPaymentMethod ret = new ChargeRequestPaymentMethod();
                        ret.setActualInstance(adapterPaymentMethodBoleto.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'PaymentMethodBoleto'", e);
                    }

                    // deserialize PaymentMethodCard
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PaymentMethodCard.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'PaymentMethodCard'");
                        ChargeRequestPaymentMethod ret = new ChargeRequestPaymentMethod();
                        ret.setActualInstance(adapterPaymentMethodCard.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'PaymentMethodCard'", e);
                    }

                    // deserialize PaymentMethodPix
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PaymentMethodPix.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'PaymentMethodPix'");
                        ChargeRequestPaymentMethod ret = new ChargeRequestPaymentMethod();
                        ret.setActualInstance(adapterPaymentMethodPix.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'PaymentMethodPix'", e);
                    }


                    throw new IOException(String.format("Failed deserialization for ChargeRequestPaymentMethod: no class matched. JSON: %s", jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public ChargeRequestPaymentMethod() {
        super("anyOf", Boolean.FALSE);
    }

    public ChargeRequestPaymentMethod(PaymentMethodBoleto o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ChargeRequestPaymentMethod(PaymentMethodCard o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ChargeRequestPaymentMethod(PaymentMethodPix o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PaymentMethodBoleto", new GenericType<PaymentMethodBoleto>() {
        });
        schemas.put("PaymentMethodCard", new GenericType<PaymentMethodCard>() {
        });
        schemas.put("PaymentMethodPix", new GenericType<PaymentMethodPix>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return ChargeRequestPaymentMethod.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * PaymentMethodBoleto, PaymentMethodCard, PaymentMethodPix
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof PaymentMethodBoleto) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof PaymentMethodCard) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof PaymentMethodPix) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PaymentMethodBoleto, PaymentMethodCard, PaymentMethodPix");
    }

    /**
     * Get the actual instance, which can be the following:
     * PaymentMethodBoleto, PaymentMethodCard, PaymentMethodPix
     *
     * @return The actual instance (PaymentMethodBoleto, PaymentMethodCard, PaymentMethodPix)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PaymentMethodBoleto`. If the actual instance is not `PaymentMethodBoleto`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PaymentMethodBoleto`
     * @throws ClassCastException if the instance is not `PaymentMethodBoleto`
     */
    public PaymentMethodBoleto getPaymentMethodBoleto() throws ClassCastException {
        return (PaymentMethodBoleto)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PaymentMethodCard`. If the actual instance is not `PaymentMethodCard`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PaymentMethodCard`
     * @throws ClassCastException if the instance is not `PaymentMethodCard`
     */
    public PaymentMethodCard getPaymentMethodCard() throws ClassCastException {
        return (PaymentMethodCard)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PaymentMethodPix`. If the actual instance is not `PaymentMethodPix`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PaymentMethodPix`
     * @throws ClassCastException if the instance is not `PaymentMethodPix`
     */
    public PaymentMethodPix getPaymentMethodPix() throws ClassCastException {
        return (PaymentMethodPix)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ChargeRequestPaymentMethod
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate anyOf schemas one by one
    int validCount = 0;
    // validate the json string with PaymentMethodBoleto
    try {
      PaymentMethodBoleto.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    // validate the json string with PaymentMethodCard
    try {
      PaymentMethodCard.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    // validate the json string with PaymentMethodPix
    try {
      PaymentMethodPix.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    if (validCount == 0) {
      throw new IOException(String.format("The JSON string is invalid for ChargeRequestPaymentMethod with anyOf schemas: PaymentMethodBoleto, PaymentMethodCard, PaymentMethodPix. JSON: %s", jsonObj.toString()));
    }
  }

 /**
  * Create an instance of ChargeRequestPaymentMethod given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChargeRequestPaymentMethod
  * @throws IOException if the JSON string is invalid with respect to ChargeRequestPaymentMethod
  */
  public static ChargeRequestPaymentMethod fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChargeRequestPaymentMethod.class);
  }

  public static Gson getGson() {
    return JSON.getGson();
  }

 /**
  * Convert an instance of ChargeRequestPaymentMethod to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

