/*
 * Malga API Documentation
 * # Authentication  Malga’s API services are protected through access keys. 
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.malga.client.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.malga.client.api.model.SourceTypeCard;
import com.malga.client.api.model.SourceTypeCardOneShot;
import com.malga.client.api.model.SourceTypeCardOneShotCard;
import com.malga.client.api.model.SourceTypeCustomer;
import com.malga.client.api.model.SourceTypeCustomerOneShot;
import com.malga.client.api.model.SourceTypeCustomerOneShotCustomer;
import com.malga.client.api.model.SourceTypeToken;
import java.io.IOException;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import com.malga.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-21T00:10:35.774518-03:00[America/Sao_Paulo]")
public class ChargeRequestPaymentSource extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ChargeRequestPaymentSource.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ChargeRequestPaymentSource.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ChargeRequestPaymentSource' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SourceTypeCard> adapterSourceTypeCard = gson.getDelegateAdapter(this, TypeToken.get(SourceTypeCard.class));
            final TypeAdapter<SourceTypeCardOneShot> adapterSourceTypeCardOneShot = gson.getDelegateAdapter(this, TypeToken.get(SourceTypeCardOneShot.class));
            final TypeAdapter<SourceTypeCustomer> adapterSourceTypeCustomer = gson.getDelegateAdapter(this, TypeToken.get(SourceTypeCustomer.class));
            final TypeAdapter<SourceTypeCustomerOneShot> adapterSourceTypeCustomerOneShot = gson.getDelegateAdapter(this, TypeToken.get(SourceTypeCustomerOneShot.class));
            final TypeAdapter<SourceTypeToken> adapterSourceTypeToken = gson.getDelegateAdapter(this, TypeToken.get(SourceTypeToken.class));

            return (TypeAdapter<T>) new TypeAdapter<ChargeRequestPaymentSource>() {
                @Override
                public void write(JsonWriter out, ChargeRequestPaymentSource value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `SourceTypeCard`
                    if (value.getActualInstance() instanceof SourceTypeCard) {
                        JsonObject obj = adapterSourceTypeCard.toJsonTree((SourceTypeCard)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `SourceTypeCardOneShot`
                    if (value.getActualInstance() instanceof SourceTypeCardOneShot) {
                        JsonObject obj = adapterSourceTypeCardOneShot.toJsonTree((SourceTypeCardOneShot)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `SourceTypeCustomer`
                    if (value.getActualInstance() instanceof SourceTypeCustomer) {
                        JsonObject obj = adapterSourceTypeCustomer.toJsonTree((SourceTypeCustomer)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `SourceTypeCustomerOneShot`
                    if (value.getActualInstance() instanceof SourceTypeCustomerOneShot) {
                        JsonObject obj = adapterSourceTypeCustomerOneShot.toJsonTree((SourceTypeCustomerOneShot)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `SourceTypeToken`
                    if (value.getActualInstance() instanceof SourceTypeToken) {
                        JsonObject obj = adapterSourceTypeToken.toJsonTree((SourceTypeToken)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: SourceTypeCard, SourceTypeCardOneShot, SourceTypeCustomer, SourceTypeCustomerOneShot, SourceTypeToken");
                }

                @Override
                public ChargeRequestPaymentSource read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize SourceTypeCard
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SourceTypeCard.validateJsonObject(jsonObject);
                        actualAdapter = adapterSourceTypeCard;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SourceTypeCard'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SourceTypeCard failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SourceTypeCard'", e);
                    }

                    // deserialize SourceTypeCardOneShot
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SourceTypeCardOneShot.validateJsonObject(jsonObject);
                        actualAdapter = adapterSourceTypeCardOneShot;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SourceTypeCardOneShot'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SourceTypeCardOneShot failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SourceTypeCardOneShot'", e);
                    }

                    // deserialize SourceTypeCustomer
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SourceTypeCustomer.validateJsonObject(jsonObject);
                        actualAdapter = adapterSourceTypeCustomer;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SourceTypeCustomer'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SourceTypeCustomer failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SourceTypeCustomer'", e);
                    }

                    // deserialize SourceTypeCustomerOneShot
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SourceTypeCustomerOneShot.validateJsonObject(jsonObject);
                        actualAdapter = adapterSourceTypeCustomerOneShot;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SourceTypeCustomerOneShot'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SourceTypeCustomerOneShot failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SourceTypeCustomerOneShot'", e);
                    }

                    // deserialize SourceTypeToken
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SourceTypeToken.validateJsonObject(jsonObject);
                        actualAdapter = adapterSourceTypeToken;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SourceTypeToken'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SourceTypeToken failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SourceTypeToken'", e);
                    }

                    if (match == 1) {
                        ChargeRequestPaymentSource ret = new ChargeRequestPaymentSource();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for ChargeRequestPaymentSource: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public ChargeRequestPaymentSource() {
        super("oneOf", Boolean.FALSE);
    }

    public ChargeRequestPaymentSource(SourceTypeCard o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ChargeRequestPaymentSource(SourceTypeCardOneShot o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ChargeRequestPaymentSource(SourceTypeCustomer o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ChargeRequestPaymentSource(SourceTypeCustomerOneShot o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ChargeRequestPaymentSource(SourceTypeToken o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("SourceTypeCard", new GenericType<SourceTypeCard>() {
        });
        schemas.put("SourceTypeCardOneShot", new GenericType<SourceTypeCardOneShot>() {
        });
        schemas.put("SourceTypeCustomer", new GenericType<SourceTypeCustomer>() {
        });
        schemas.put("SourceTypeCustomerOneShot", new GenericType<SourceTypeCustomerOneShot>() {
        });
        schemas.put("SourceTypeToken", new GenericType<SourceTypeToken>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return ChargeRequestPaymentSource.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * SourceTypeCard, SourceTypeCardOneShot, SourceTypeCustomer, SourceTypeCustomerOneShot, SourceTypeToken
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof SourceTypeCard) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SourceTypeCardOneShot) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SourceTypeCustomer) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SourceTypeCustomerOneShot) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SourceTypeToken) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be SourceTypeCard, SourceTypeCardOneShot, SourceTypeCustomer, SourceTypeCustomerOneShot, SourceTypeToken");
    }

    /**
     * Get the actual instance, which can be the following:
     * SourceTypeCard, SourceTypeCardOneShot, SourceTypeCustomer, SourceTypeCustomerOneShot, SourceTypeToken
     *
     * @return The actual instance (SourceTypeCard, SourceTypeCardOneShot, SourceTypeCustomer, SourceTypeCustomerOneShot, SourceTypeToken)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `SourceTypeCard`. If the actual instance is not `SourceTypeCard`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SourceTypeCard`
     * @throws ClassCastException if the instance is not `SourceTypeCard`
     */
    public SourceTypeCard getSourceTypeCard() throws ClassCastException {
        return (SourceTypeCard)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SourceTypeCardOneShot`. If the actual instance is not `SourceTypeCardOneShot`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SourceTypeCardOneShot`
     * @throws ClassCastException if the instance is not `SourceTypeCardOneShot`
     */
    public SourceTypeCardOneShot getSourceTypeCardOneShot() throws ClassCastException {
        return (SourceTypeCardOneShot)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SourceTypeCustomer`. If the actual instance is not `SourceTypeCustomer`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SourceTypeCustomer`
     * @throws ClassCastException if the instance is not `SourceTypeCustomer`
     */
    public SourceTypeCustomer getSourceTypeCustomer() throws ClassCastException {
        return (SourceTypeCustomer)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SourceTypeCustomerOneShot`. If the actual instance is not `SourceTypeCustomerOneShot`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SourceTypeCustomerOneShot`
     * @throws ClassCastException if the instance is not `SourceTypeCustomerOneShot`
     */
    public SourceTypeCustomerOneShot getSourceTypeCustomerOneShot() throws ClassCastException {
        return (SourceTypeCustomerOneShot)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SourceTypeToken`. If the actual instance is not `SourceTypeToken`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SourceTypeToken`
     * @throws ClassCastException if the instance is not `SourceTypeToken`
     */
    public SourceTypeToken getSourceTypeToken() throws ClassCastException {
        return (SourceTypeToken)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ChargeRequestPaymentSource
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with SourceTypeCard
    try {
      SourceTypeCard.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SourceTypeCard failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SourceTypeCardOneShot
    try {
      SourceTypeCardOneShot.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SourceTypeCardOneShot failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SourceTypeCustomer
    try {
      SourceTypeCustomer.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SourceTypeCustomer failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SourceTypeCustomerOneShot
    try {
      SourceTypeCustomerOneShot.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SourceTypeCustomerOneShot failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SourceTypeToken
    try {
      SourceTypeToken.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SourceTypeToken failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for ChargeRequestPaymentSource with oneOf schemas: SourceTypeCard, SourceTypeCardOneShot, SourceTypeCustomer, SourceTypeCustomerOneShot, SourceTypeToken. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonObj.toString()));
    }
  }

 /**
  * Create an instance of ChargeRequestPaymentSource given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChargeRequestPaymentSource
  * @throws IOException if the JSON string is invalid with respect to ChargeRequestPaymentSource
  */
  public static ChargeRequestPaymentSource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChargeRequestPaymentSource.class);
  }

 /**
  * Convert an instance of ChargeRequestPaymentSource to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

