/*
 * Malga API Documentation
 * # Authentication  Malga’s API services are protected through access keys. 
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.malga.client.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.malga.client.api.model.SessionChargeRequestFraudAnalysis;
import io.malga.client.api.model.SessionChargeRequestPaymentMethod;
import io.malga.client.api.model.SessionChargeRequestPaymentSource;
import java.io.IOException;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.malga.client.JSON;

/**
 * SessionChargeRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-27T15:34:15.656627-03:00[America/Sao_Paulo]")
public class SessionChargeRequest {
  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  private UUID customerId;

  public static final String SERIALIZED_NAME_PAYMENT_METHOD = "paymentMethod";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD)
  private SessionChargeRequestPaymentMethod paymentMethod;

  public static final String SERIALIZED_NAME_PAYMENT_SOURCE = "paymentSource";
  @SerializedName(SERIALIZED_NAME_PAYMENT_SOURCE)
  private SessionChargeRequestPaymentSource paymentSource;

  public static final String SERIALIZED_NAME_FRAUD_ANALYSIS = "fraudAnalysis";
  @SerializedName(SERIALIZED_NAME_FRAUD_ANALYSIS)
  private SessionChargeRequestFraudAnalysis fraudAnalysis;

  public SessionChargeRequest() {
  }

  public SessionChargeRequest customerId(UUID customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Customer identification
   * @return customerId
  **/
  @javax.annotation.Nullable

  public UUID getCustomerId() {
    return customerId;
  }


  public void setCustomerId(UUID customerId) {
    this.customerId = customerId;
  }


  public SessionChargeRequest paymentMethod(SessionChargeRequestPaymentMethod paymentMethod) {
    
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @javax.annotation.Nonnull

  public SessionChargeRequestPaymentMethod getPaymentMethod() {
    return paymentMethod;
  }


  public void setPaymentMethod(SessionChargeRequestPaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public SessionChargeRequest paymentSource(SessionChargeRequestPaymentSource paymentSource) {
    
    this.paymentSource = paymentSource;
    return this;
  }

   /**
   * Get paymentSource
   * @return paymentSource
  **/
  @javax.annotation.Nonnull

  public SessionChargeRequestPaymentSource getPaymentSource() {
    return paymentSource;
  }


  public void setPaymentSource(SessionChargeRequestPaymentSource paymentSource) {
    this.paymentSource = paymentSource;
  }


  public SessionChargeRequest fraudAnalysis(SessionChargeRequestFraudAnalysis fraudAnalysis) {
    
    this.fraudAnalysis = fraudAnalysis;
    return this;
  }

   /**
   * Get fraudAnalysis
   * @return fraudAnalysis
  **/
  @javax.annotation.Nullable

  public SessionChargeRequestFraudAnalysis getFraudAnalysis() {
    return fraudAnalysis;
  }


  public void setFraudAnalysis(SessionChargeRequestFraudAnalysis fraudAnalysis) {
    this.fraudAnalysis = fraudAnalysis;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SessionChargeRequest instance itself
   */
  public SessionChargeRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionChargeRequest sessionChargeRequest = (SessionChargeRequest) o;
    return Objects.equals(this.customerId, sessionChargeRequest.customerId) &&
        Objects.equals(this.paymentMethod, sessionChargeRequest.paymentMethod) &&
        Objects.equals(this.paymentSource, sessionChargeRequest.paymentSource) &&
        Objects.equals(this.fraudAnalysis, sessionChargeRequest.fraudAnalysis)&&
        Objects.equals(this.additionalProperties, sessionChargeRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, paymentMethod, paymentSource, fraudAnalysis, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionChargeRequest {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    paymentSource: ").append(toIndentedString(paymentSource)).append("\n");
    sb.append("    fraudAnalysis: ").append(toIndentedString(fraudAnalysis)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customerId");
    openapiFields.add("paymentMethod");
    openapiFields.add("paymentSource");
    openapiFields.add("fraudAnalysis");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("paymentMethod");
    openapiRequiredFields.add("paymentSource");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SessionChargeRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SessionChargeRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SessionChargeRequest is not found in the empty JSON string", SessionChargeRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SessionChargeRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("customerId") != null && !jsonObj.get("customerId").isJsonNull()) && !jsonObj.get("customerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerId").toString()));
      }
      // validate the required field `paymentMethod`
      SessionChargeRequestPaymentMethod.validateJsonObject(jsonObj.getAsJsonObject("paymentMethod"));
      // validate the required field `paymentSource`
      SessionChargeRequestPaymentSource.validateJsonObject(jsonObj.getAsJsonObject("paymentSource"));
      // validate the optional field `fraudAnalysis`
      if (jsonObj.get("fraudAnalysis") != null && !jsonObj.get("fraudAnalysis").isJsonNull()) {
        SessionChargeRequestFraudAnalysis.validateJsonObject(jsonObj.getAsJsonObject("fraudAnalysis"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SessionChargeRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SessionChargeRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SessionChargeRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SessionChargeRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SessionChargeRequest>() {
           @Override
           public void write(JsonWriter out, SessionChargeRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SessionChargeRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SessionChargeRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SessionChargeRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SessionChargeRequest
  * @throws IOException if the JSON string is invalid with respect to SessionChargeRequest
  */
  public static SessionChargeRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SessionChargeRequest.class);
  }

 /**
  * Convert an instance of SessionChargeRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

