/*
 * Malga API Documentation
 * # Authentication  Malga’s API services are protected through access keys. 
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.malga.client.api;

import io.malga.client.ApiException;
import io.malga.model.cards.CardRequest;
import io.malga.model.cards.CardResponse;
import io.malga.model.cards.TokenRequest;
import io.malga.model.cards.TokenResponse;
import io.malga.service.cards.CardsApi;
import io.malga.service.cards.TokensApi;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;


/**
 * API tests for CardsApi
 */
public class CardsApiTest extends BaseApiTest{

    /**
     * Get card details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCardByIdTest() throws ApiException {
        TokensApi tokenApi = new TokensApi(this.getDefaulClientApi());
        TokenRequest tokenRequest = this.createTokenRequest();
        TokenResponse tokenResponse = tokenApi.createToken(tokenRequest);

        CardsApi cardApi = new CardsApi(this.getDefaulClientApi());
        CardRequest cardRequest = ((new CardRequest())
                .tokenId(tokenResponse.getTokenId())
                .merchantId(System.getenv("MERCHANT_ID"))
                .cvvCheck(true)
        );

        CardResponse createResponse = cardApi.createCard(cardRequest);

        CardResponse cardResponse = cardApi.getCardById(createResponse.getId());

        assertNotNull(cardResponse.getId());
        assertNotNull(cardResponse.getCreatedAt());
        assertEquals(CardResponse.BrandEnum.VISA, cardResponse.getBrand());
        assertEquals(true, cardResponse.getCvvChecked());
        assertEquals("12", cardResponse.getExpirationMonth());
        assertEquals("2025", cardResponse.getExpirationYear());
        assertEquals("492956", cardResponse.getFirst6digits());
        assertEquals("7814", cardResponse.getLast4digits());
        assertEquals(CardResponse.StatusEnum.ACTIVE, cardResponse.getStatus());
    }

//    /**
//     * List cards
//     *
//     * @throws ApiException if the Api call fails
//     */
//    @Test
//    public void getCardsTest() throws ApiException {
//        String page = null;
//        String limit = null;
//        CardList response = api.getCards(page, limit);
//        // TODO: test validations
//    }

    /**
     * Create a new card from card token
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void saveCardTest() throws ApiException {
        TokensApi tokenApi = new TokensApi(this.getDefaulClientApi());
        TokenRequest tokenRequest = this.createTokenRequest();
        TokenResponse tokenResponse = tokenApi.createToken(tokenRequest);

        CardsApi cardApi = new CardsApi(this.getDefaulClientApi());
        CardRequest cardRequest = ((new CardRequest())
                .tokenId(tokenResponse.getTokenId())
                .merchantId(System.getenv("MERCHANT_ID"))
                .cvvCheck(true)
        );

        CardResponse cardResponse = cardApi.createCard(cardRequest);

        assertNotNull(cardResponse.getId());
        assertNotNull(cardResponse.getCreatedAt());
        assertEquals(CardResponse.BrandEnum.VISA, cardResponse.getBrand());
        assertEquals(true, cardResponse.getCvvChecked());
        assertEquals("12", cardResponse.getExpirationMonth());
        assertEquals("2025", cardResponse.getExpirationYear());
        assertEquals("492956", cardResponse.getFirst6digits());
        assertEquals("7814", cardResponse.getLast4digits());
        assertEquals(CardResponse.StatusEnum.ACTIVE, cardResponse.getStatus());
    }

}
