/*
 * Malga API Documentation
 * # Authentication  Malga’s API services are protected through access keys. 
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.malga.client.api;

import io.malga.client.ApiException;
import io.malga.model.clienttoken.AuthRequest;
import io.malga.model.clienttoken.AuthResponse;
import io.malga.service.clienttoken.ClientTokenApi;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

/**
 * API tests for ClientTokenApi
 */
public class ClientTokenApiTest extends BaseApiTest{



    /**
     * Create public key for client-side integration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAuthTokenTest() throws ApiException {
        ClientTokenApi clientTokenApi = new ClientTokenApi(this.getDefaulClientApi());
        AuthRequest authRequest = ((new AuthRequest())
                .expires(3600)
                .scope(List.of(AuthRequest.ScopeEnum.TOKENS))
        );
        AuthResponse authResponse = clientTokenApi.createClientToken(authRequest);

        Assertions.assertNotNull(authResponse.getPublicKey());
    }

}
